# Generated by Django 6.0.7 on 2026-07-29 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0003_remove_module_created_by_remove_module_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_year', models.CharField(help_text='e.g. "2025/2026"', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ['-school_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='classes.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='quizzes.topic')),
            ],
            options={
                'ordering': ['school_class__name', 'topic__name'],
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quizzes.quiz')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='classes.class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='classes.teachinggroup')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='classes.enrollment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='classes.teachinggroup')),
            ],
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('name', 'school_year', 'created_by'), name='uniq_class_per_year_per_teacher'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'school_class'), name='uniq_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='teachinggroup',
            constraint=models.UniqueConstraint(fields=('school_class', 'topic', 'teacher'), name='uniq_teaching_group'),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('school_class__isnull', False), ('student__isnull', True)), models.Q(('group__isnull', False), ('school_class__isnull', True), ('student__isnull', True)), models.Q(('group__isnull', True), ('school_class__isnull', True), ('student__isnull', False)), _connector='OR'), name='quizassignment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('school_class__isnull', False)), fields=('quiz', 'school_class'), name='uniq_assignment_class'),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('quiz', 'group'), name='uniq_assignment_group'),
        ),
        migrations.AddConstraint(
            model_name='quizassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('quiz', 'student'), name='uniq_assignment_student'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'enrollment'), name='uniq_group_membership'),
        ),
    ]
