# Generated by Django 6.0.7 on 2026-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmembership',
            options={'ordering': ['enrollment__student__last_name', 'enrollment__student__first_name']},
        ),
    ]
