# Generated by Django 6.0.6 on 2026-07-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attempts', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField(help_text='Inclusive lower bound, percent')),
                ('max_score', models.PositiveIntegerField(help_text='Inclusive upper bound, percent')),
                ('feedback_text', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_rules', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_rules', to='quizzes.module')),
            ],
            options={
                'ordering': ['module', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.FloatField()),
                ('feedback_text', models.TextField()),
                ('source', models.CharField(choices=[('rule', 'Teacher rule'), ('llm', 'LLM generated')], default='rule', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_results', to='attempts.quizattempt')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_results', to='quizzes.module')),
            ],
            options={
                'unique_together': {('attempt', 'module')},
            },
        ),
    ]
