# Generated by Django 6.0.7 on 2026-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_per_choice_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresult',
            name='module_feedback_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
