import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import "./globals.css";

// Inter is a variable font, so it needs no `weight` — Guidelines §3 asks for
// 400/500/600 and the variable axis covers all three. Space Mono is not
// variable, so its weights must be listed explicitly.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Evalio",
  description: "Quizzes with an explanation for every wrong answer.",
};

// `LayoutProps` is a global generated by `next typegen` (which `next dev` and
// `next build` also run). It is route-aware, so a nested layout writes
// `LayoutProps<'/quizzes/[id]'>` and gets a correctly typed `params`.
// It is global on purpose — do not import it.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceMono.variable}`}>
      {/* The page ground is --color-canvas, not --color-background. Cards are
          white and lift off the ground by value *and* by a hairline shadow.
          The ground carries the palette's cool cast so the brand blue reads as
          native to it rather than applied on top. */}
      <body className="min-h-screen bg-canvas font-sans text-foreground antialiased">
        {children}
      </body>
    </html>
  );
}
