import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Evalio",
  description: "Quizzes with an explanation for every wrong answer.",
};

// `LayoutProps` is a global generated by `next typegen` (which `next dev` and
// `next build` also run). It is route-aware, so a nested layout writes
// `LayoutProps<'/quizzes/[id]'>` and gets a correctly typed `params`.
// It is global on purpose — do not import it.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
