# Generated by Django 6.0.7 on 2026-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='feedback_text',
            field=models.TextField(blank=True, default='', help_text='Explanation shown to a student who picks this choice. Written by the teacher, mainly to explain why an incorrect choice is wrong.'),
        ),
    ]
