# Generated by Django 6.0.7 on 2026-07-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_choice_feedback_text'),
        # Module cannot be deleted until every other app has stopped referencing it.
        # feedback.0001 creates FeedbackRule/FeedbackResult with FKs to quizzes.module
        # and feedback.0002 removes them; without this edge the graph is free to run
        # DeleteModel first, which fails on a database built from scratch (the test
        # database) while appearing fine on one where feedback.0002 already ran.
        ('feedback', '0002_per_choice_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='question',
            name='module',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='questionbank',
            name='name',
            field=models.CharField(default='Uncategorised', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Controls whether assigned students can see and start this quiz. A soft flag — a published quiz stays editable, and un-publishing leaves existing attempts and their feedback intact.'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='quizzes.topic'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='uniq_bank_name_per_topic'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
