# Generated by Django 6.0.7 on 2026-07-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='ai_feedback_text',
            field=models.TextField(blank=True, default='', help_text="AI-drafted explanation for this choice. Written only by the generation service, only when `feedback_text` is blank, and never shown to a student unless the quiz's feedback_mode is 'ai'."),
        ),
        migrations.AddField(
            model_name='choice',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='feedback_mode',
            field=models.CharField(choices=[('teacher', 'Teacher-written only'), ('ai', 'AI-drafted, with teacher-written taking precedence')], default='teacher', max_length=10),
        ),
        migrations.AddField(
            model_name='topic',
            name='feedback_prompt',
            field=models.TextField(blank=True, default='', help_text="Optional tone and detail instructions for AI-drafted feedback in this topic — e.g. 'Year 3 pupils, two short sentences, warm and concrete.' Layered on top of the built-in template; it does not replace it."),
        ),
    ]
