# Generated by Django 6.0.7 on 2026-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_choice_ai_feedback_text_choice_ai_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='shuffle_choices',
            field=models.BooleanField(default=False, help_text="Present each question's choices in a per-student random order at attempt time."),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Present the questions in a per-student random order at attempt time.'),
        ),
    ]
