# Generated by Django 6.0.7 on 2026-08-24 11:03

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_shuffle_choices_quiz_shuffle_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='quizzes.quiz')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Which module this question counts toward for per-module feedback. Optional — an unassigned question still counts toward the overall score but contributes to no module breakdown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='quizzes.quizmodule'),
        ),
        migrations.AddConstraint(
            model_name='quizmodule',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('quiz'), name='uniq_quizmodule_name_per_quiz_ci'),
        ),
    ]
