# Generated by Django 6.0.7 on 2026-07-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('quizzes', '0003_remove_module_created_by_remove_module_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='choice_feedback_text',
            field=models.TextField(blank=True, default='', help_text="Snapshot of the chosen choice's teacher-written explanation. Never serialized to a student — it reaches them only inside the assembled FeedbackResult after they submit."),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='choice_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='answerresponse',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='answerresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='quizzes.question'),
        ),
        migrations.AlterField(
            model_name='answerresponse',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.choice'),
        ),
    ]
