# Generated by Django 6.0.7 on 2026-07-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresponse',
            name='choice_ai_feedback_text',
            field=models.TextField(blank=True, default='', help_text="Snapshot of the chosen choice's AI-drafted explanation. Same exposure rule as choice_feedback_text — never serialized to a student."),
        ),
    ]
