# Generated by Django 6.0.7 on 2026-08-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0003_answerresponse_choice_ai_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerresponse',
            name='module_name',
            field=models.CharField(blank=True, default='', help_text="Snapshot of the quiz-question's module name at answer time, for per-module feedback. Blank if the question had no module. Never re-read from the live QuizQuestion when rebuilding feedback, for the same reason question_text and choice_text aren't.", max_length=100),
        ),
    ]
