"""
Django settings for evalio project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Read from the environment like the POSTGRES_* settings below. The fallback exists so
# a fresh clone runs without a .env; it is only reached in DEBUG and must never be the
# value in a deployed environment.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-!jqbw&k(2=oslwjn!2-+2ij+a1zv7eir9twa%*hxtleti^zly%",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    host for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if host
]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'accounts',
    'quizzes',
    'feedback',
    'attempts',
    'classes',
    # Read-only: owns no models, only ways of asking about the others'.
    'analytics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # must sit high, before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js dev server
]
# Transitional. Under the planned BFF the browser only ever talks to same-origin
# route handlers on :3000, which forward to Django server-to-server — a hop CORS does
# not apply to. Once the frontend proxies everything, this setting and `corsheaders`
# can be removed rather than corrected.

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    # Every list response is {count, next, previous, results} — not a bare array.
    # Unpaginated list endpoints returned whole tables, and the bank contents screen
    # is explicitly a search over a large question list.
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 25,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# --- AI-drafted feedback -------------------------------------------------------
#
# Authoring-time only. Nothing in this block runs while a student is taking or
# submitting a quiz: per-choice explanations depend on the *content*, not on the
# attempt, so they are drafted once by the teacher and then snapshotted like any
# other explanation. See docs/BACKEND.md §7.
#
# Read server-side in Django only. These never reach the browser, so the frontend
# needs none of them.

GOOGLE_AI_API_KEY = os.environ.get("GOOGLE_AI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")

# DeepSeek, read only by feedback/providers/deepseek.py. Self-contained the same way
# the Gemini vars are: a provider owns its key/model/endpoint, so swapping providers
# is one AI_FEEDBACK_PROVIDER line and never a rename of the shared key. Base URL and
# model have working defaults, so pasting DEEPSEEK_API_KEY is enough to start.
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.environ.get("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-chat")

# Defaults **false**, so a fresh clone, a CI run and a forgotten .env can never
# spend a token or reach the network by accident. The endpoints answer 503 while
# it is off rather than failing somewhere deeper and less legibly.
AI_FEEDBACK_ENABLED = os.environ.get("AI_FEEDBACK_ENABLED", "false").lower() in (
    "1", "true", "yes",
)

# Seconds here; the Gemini SDK wants milliseconds and `GeminiProvider` converts.
AI_FEEDBACK_TIMEOUT = float(os.environ.get("AI_FEEDBACK_TIMEOUT", "30"))

# How many questions are drafted at once, and the ceiling the pacer holds the run
# under. Requests-per-minute is the constraint that bites first on a free key, and
# it is not the same thing as concurrency: 4 in flight against a 5 RPM key is a
# burst of 429s. The pacer spaces requests to AI_FEEDBACK_RPM regardless of how
# many workers are waiting, so raising concurrency alone can never breach the
# quota. Raise both together after enabling billing.
AI_FEEDBACK_CONCURRENCY = int(os.environ.get("AI_FEEDBACK_CONCURRENCY", "2"))
AI_FEEDBACK_RPM = int(os.environ.get("AI_FEEDBACK_RPM", "5"))

# Blank by default, meaning **send no thinking config at all** and let the model use
# its own. This is deliberately the safe default rather than the cheap one: the
# knob is model-generation-specific — 2.5 takes a `thinking_budget` in tokens where
# 0 disables it, Gemini 3 models take a `thinking_level` instead and reject a
# budget — so a hard-coded value silently ties this project to one model family and
# fails the whole run when you change GEMINI_MODEL.
#
# Set it to an integer only if you know your model accepts one: 0 turns thinking off
# on 2.5 Flash, which a two-sentence explanation does not need and which saves
# latency and output tokens.
_thinking_budget = os.environ.get("AI_FEEDBACK_THINKING_BUDGET", "").strip()
AI_FEEDBACK_THINKING_BUDGET = int(_thinking_budget) if _thinking_budget else None

# A runaway response is a bug, not a feature — the prompt asks for two or three
# sentences. A draft longer than this fails its question rather than being written.
AI_FEEDBACK_MAX_LENGTH = 800

# Dotted path, so the provider is injected rather than imported directly by the
# service. This is what lets the test runner below swap in a deterministic fake
# without a single test knowing that GeminiProvider exists.
AI_FEEDBACK_PROVIDER = os.environ.get(
    "AI_FEEDBACK_PROVIDER", "feedback.providers.gemini.GeminiProvider"
)

# §10 of the plan this implements: *nothing in the test suite may touch the
# network*. Enforcing that per-test would mean every future test remembering to
# override the provider, and the one that forgets spends real tokens against the
# developer's own key. The runner forces the fake for the whole suite instead.
TEST_RUNNER = "evalio.testrunner.EvalioTestRunner"

ROOT_URLCONF = 'evalio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evalio.wsgi.application'

LOGIN_REDIRECT_URL = "/api/auth/me/"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
    }
}

AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
